export const HIGH_SCHOOL_MANAGER = 'HIGH_SCHOOL_MANAGER'
export const UNIVERSITY_MANAGER = 'UNIVERSITY_MANAGER'
export const ORGANIZATION_MANAGER = 'ORGANIZATION'
export const HIGH_SCHOOL_STUDENT = 'HIGH_SCHOOL_STUDENT'
