export const PATH = {
  INDEX: '/',
  LOGIN: '/auth/login',
  FORGOT_PASSWORD: '/auth/forgot-password',
  CHANGE_PASSWORD: '/auth/change-password',
  REGISTRATION: '/auth/registration',
  POLICY: '/policy',
  UPDATE_PROFILE: '/auth/update-profile',
  SCHEDULE_EVENT: '/schedule',
  DETAIL_EVENT: '/detail-event',
  LIST_EVENT_FOR_HIGH_SCHOOL: '/event-for-highschool',
  LIST_MAJOR_GROUP: '/major-groups',
  DETAIL_MAJOR_GROUP: '/major-group-detail',
  ABOUT_US: '/about-us',
  ACCOUNT_WAITING_APPROVE: '/auth/pending',
  EVENT_PAGE: '/event/:eventId',
  NEW_PAGE: '/new/:newId',
  UNIVERSITY_PROFILE_PAGE: '/university/:universityId',
  NEW: '/new/',
  EVENT: '/event/',
  PAGE_NOT_FOUND: '/404'
};
export const PATH_HIGH_SCHOOL_MANAGER = {
  INDEX: '/',
  SLOT_MANAGER: '/high-school/slot-manage',
  LIST_EVENT: '/high-school/events',
  VIEW_PROFILE: '/high-school/view-profile',
  EDIT_PROFILE: '/high-school/edit-profile',
  REGISTERED_EVENT: '/high-school/registered-events',
  LIST_STUDENT: '/high-school/students',
  PROFILE: '/high-school/profile',
  LIST_ACCOUNT_PENDING: '/high-school/account',
  ACCOUNT_PROFILE: '/high-school/account-profile'
};
export const PATH_UNIVERSITY_MANAGER = {
  INDEX: '/',
  NEW: '/uni/list-new',
  LIST_EVENT: '/uni/events',
  REGIS_EVENT: '/uni/register-event',
  MANAGE_EVENT: '/uni/manage-event',
  PROFILE: '/uni/university-detail',
  BOOKING_EVENT: '/uni/event-booking',
  CALENDAR: '/uni/calendar',
  UPDATE_PROFILE: '/uni/update-profile',
  REGISTERED_EVENT: '/uni/registered-event',
  CREATE_NEW: '/uni/create-new',
  MANAGE_BOOKING: '/uni/event',
  GOAL_ADMISSION: '/uni/goal-admission',
  MANAGE_NEWS: '/uni/new',
  LIST_ACCOUNT_PENDING: '/uni/account',
  PUBLIC_EVENT: '/uni/public-event',
  UN_PUBLIC_EVENT: '/uni/unpublic-event',
  EVENT_CHECK: '/uni/event-check',
  ANALYTICS_DATA: '/uni/analytics-student-data',
  ACCOUNT_PROFILE: '/uni/account-profile'
};
export const PATH_HIGH_SCHOOL_STUDENT = {
  INDEX: '/',
  LIST_EVENT: '/student/events',
  DETAIL_EVENT: '/student/event-detail',
  PROFILE: '/student/profile',
  NEWS: '/student/news',
  NEWS_DETAIL: '/student/news-detail',
  UPDATE_PROFILE: '/student/update-profile',
  CERTIFICATION: '/student/certification',
  SCORE: '/student/score',
  HIGH_SCHOOL_PROFILE: '/student/highschool-profile',
  LIST_UNIVERSITY: '/student/list-university',
  PROFILE_UNIVERSITY: '/student/university-detail'
};
